### ISSUE TITLE
Automatic posting to Twitter not working.

### ISSUE THREAD

**Issue by Bizarre57** [tweeklyfm/tweeklyfm#5]
Hi.  Automatic updates are not working.  This error code appears on my Dashboard: API Error: Client error response [status code] 401 [reason phrase] Authorization Required [url] https://api.twitter.com/1.1/statuses/update.json

Can you please assist?

Barry

**Comment by ssx** [comment]
Remove your twitter account and re-add it. Your API tokens have become invalid at some point (happens often now-a-days).
